# Generated by Django 5.2 on 2025-04-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
