# Generated by Django 5.2 on 2025-04-06 19:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_assignment_completed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('happy', '😊 Happy'), ('okay', '😐 Okay'), ('stressed', '😰 Stressed'), ('sad', '😢 Sad'), ('motivated', '💪 Motivated'), ('tired', '😴 Tired')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('checkin_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checkin_date'],
            },
        ),
    ]
